version: "2"
services:
  go-greenhouse:
    image: noodlensk/go-greenhouse:latest
    ports:
      - "8080:8080"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      GO-GREENHOUSE_PORT: "/dev/ttyACM0"